project_id = "tawtsykkppopmyxhqkbw"

[functions.send-order-otp]
verify_jwt = false

[functions.verify-order-otp]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-password-reset-otp]
verify_jwt = false

[functions.verify-password-reset-otp]
verify_jwt = false
